version: '3'
services:
  nginx:
    image: nginx:swarm
    command: nginx -g "daemon off;"
    depends_on:
      - tomcat
    ports:
      - "5000:80"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  tomcat:
    image: tomcat:swarm
    working_dir: /usr/local/tomcat
    command: catalina.sh run
    ports:
      - "6000:8080"
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 20s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  frontend:
