version: '3'
services:
  nginx:
    build: nginx
    command: nginx -g "daemon off;"
    links:
      - tomcat
    container_name: app_nginx
    ports:
      - "5000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 20s
      timeout: 10s
      retries: 3
  tomcat:
    build: tomcat
    working_dir: /usr/local/tomcat
    command: catalina.sh run
    container_name: app_tomcat
    ports:
      - "6000:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 20s
      timeout: 10s
      retries: 3
